# Generated by Django 3.1.2 on 2020-10-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('addressine1', models.CharField(max_length=60)),
                ('addressine2', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('hospital_phone_number', models.CharField(max_length=14)),
                ('licence_number', models.CharField(max_length=20)),
                ('originally_registered_date', models.DateField()),
                ('registered_date', models.DateField()),
                ('regisrted_by', models.IntegerField()),
            ],
        ),
    ]
