# Generated by Django 3.1.2 on 2021-02-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentSlots',
        ),
    ]
