# Generated by Django 3.1.2 on 2020-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='experience_at_this_hospital',
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
