# Generated by Django 3.1.2 on 2020-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201006_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='pincode',
            field=models.CharField(max_length=9),
        ),
    ]
