# Generated by Django 3.1.2 on 2021-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210207_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='security_question',
            field=models.CharField(max_length=200),
        ),
    ]
