# Generated by Django 3.1.2 on 2020-10-06 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201006_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='regisrted_by',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 10, 6)),
        ),
    ]
