# Generated by Django 3.1.2 on 2020-11-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201105_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='name',
            new_name='Name',
        ),
    ]
