# Generated by Django 3.0.5 on 2021-02-19 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210210_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='created_by',
        ),
        migrations.AddField(
            model_name='patients',
            name='allergies_to_medicine',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patients',
            name='hobbies',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='physical_activities',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='recurring_problems',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='related_profile',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='backend.Profiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='use_of_alcohol',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AddField(
            model_name='patients',
            name='use_of_tobacco',
            field=models.CharField(default='F', max_length=3),
        ),
    ]
