# Generated by Django 3.1.2 on 2020-10-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201006_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='originally_registered_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 6)),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='regisrted_by',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 6)),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 6)),
        ),
    ]
