# Generated by Django 3.1.2 on 2020-11-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201108_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_content', models.TextField()),
                ('reviewTimeStamp', models.DateTimeField()),
                ('review_stars', models.IntegerField()),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_review_by', to='backend.profiles')),
                ('review_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_review_for', to='backend.profiles')),
            ],
        ),
    ]
