# Generated by Django 3.1.2 on 2020-10-12 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201006_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='originally_registered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='regisrted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profiles'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='registered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
