# Generated by Django 3.1.2 on 2020-11-17 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewTimeStamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
