# Generated by Django 3.0.5 on 2021-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_patients_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
    ]
