# Generated by Django 3.0.5 on 2021-02-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_appointments_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_hospital', to='backend.Hospitals'),
            preserve_default=False,
        ),
    ]
