# Generated by Django 3.1.2 on 2020-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201117_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
