# Generated by Django 3.1.2 on 2020-10-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201012_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='username',
            new_name='user_name',
        ),
    ]
