# Generated by Django 3.1.2 on 2020-10-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201019_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user_name',
            new_name='username',
        ),
    ]
