# Generated by Django 3.0.5 on 2021-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_reviews_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='is_created_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
