# Generated by Django 3.0.5 on 2021-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210221_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalworkinghours',
            name='is_open_always',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
