# Generated by Django 3.1.2 on 2021-02-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_hospitals_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_pic_image', serialize=False, to='backend.profiles')),
                ('encoded_image', models.TextField()),
            ],
        ),
    ]
