# Generated by Django 3.0.5 on 2021-02-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_hospitalworkinghours_is_open_always'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=21)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hospitals')),
            ],
        ),
    ]
