# Generated by Django 3.0.5 on 2021-02-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_hospitalservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalservices',
            name='doctor',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='backend.Profiles'),
            preserve_default=False,
        ),
    ]
