# Generated by Django 3.1.2 on 2021-02-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210201_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_slot', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.department'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.lab'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='pharmacy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pharmacy'),
        ),
    ]
