# Generated by Django 3.1.2 on 2021-02-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_hospitalservices_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='pharmacy_id',
            new_name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PharmacyMedicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('working_hours', models.TextField()),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profiles')),
            ],
        ),
    ]
