# Generated by Django 3.1.2 on 2021-02-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210204_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='status',
            new_name='appointment_status',
        ),
    ]
