# Generated by Django 3.1.2 on 2021-02-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210222_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='profile_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile_id', to='backend.profiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile_id', to='backend.profiles'),
        ),
    ]
