# Generated by Django 3.1.2 on 2021-02-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210204_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorkingHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mon_start_time', models.CharField(max_length=15)),
                ('mon_end_time', models.CharField(max_length=15)),
                ('tue_start_time', models.CharField(max_length=15)),
                ('tue_end_time', models.CharField(max_length=15)),
                ('wed_start_time', models.CharField(max_length=15)),
                ('wed_end_time', models.CharField(max_length=15)),
                ('thu_start_time', models.CharField(max_length=15)),
                ('thu_end_time', models.CharField(max_length=15)),
                ('fri_start_time', models.CharField(max_length=15)),
                ('fri_end_time', models.CharField(max_length=15)),
                ('sat_start_time', models.CharField(max_length=15)),
                ('sat_end_time', models.CharField(max_length=15)),
                ('sun_start_time', models.CharField(max_length=15)),
                ('sun_end_time', models.CharField(max_length=15)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lab', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalWorkingHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mon_start_time', models.CharField(max_length=15)),
                ('mon_end_time', models.CharField(max_length=15)),
                ('tue_start_time', models.CharField(max_length=15)),
                ('tue_end_time', models.CharField(max_length=15)),
                ('wed_start_time', models.CharField(max_length=15)),
                ('wed_end_time', models.CharField(max_length=15)),
                ('thu_start_time', models.CharField(max_length=15)),
                ('thu_end_time', models.CharField(max_length=15)),
                ('fri_start_time', models.CharField(max_length=15)),
                ('fri_end_time', models.CharField(max_length=15)),
                ('sat_start_time', models.CharField(max_length=15)),
                ('sat_end_time', models.CharField(max_length=15)),
                ('sun_start_time', models.CharField(max_length=15)),
                ('sun_end_time', models.CharField(max_length=15)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hospitals', unique=True)),
            ],
        ),
    ]
