# Generated by Django 3.0.5 on 2021-03-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210308_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreports',
            name='category',
            field=models.CharField(default='NA', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreports',
            name='price',
            field=models.CharField(default=75.0, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LabReportsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_date', models.DateField()),
                ('order_status', models.CharField(max_length=30)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='backend.Profiles')),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='backend.Patients')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lab')),
                ('labreport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.LabReports')),
            ],
        ),
    ]
